### ISSUE TITLE
UN Hindi system different

### ISSUE THREAD

**Issue by ronaldtse** [interscript/jsdemo.interscript.com#14]
Interscript:

<img width="293" alt="Screen Shot 2020-10-15 at 12 19 26 PM" src="https://user-images.githubusercontent.com/11865/96076761-aba34800-0ee0-11eb-8076-64c1ce2b120c.png">

Original:
<img width="275" alt="Screen Shot 2020-10-15 at 12 19 36 PM" src="https://user-images.githubusercontent.com/11865/96076770-b1992900-0ee0-11eb-9857-530a77233883.png">

Ping @bilashsaha

**Comment by bilashsaha** [comment]
@ronaldtse The the problem in  transliteration for `Dillī` can be solved in way I can fix it with a logic. I am working on this.

But the problem is in `Bharat` as the rule says :
`It is recommended that the vowel अ (a) should always be romanized except when it ends a name. ` and the problem is how to determine that one word is a name/noun or a simple verb/adjective using regular expression? Or we shall always think that its a name ?

The transliteration for `Bharat` in this case becomes `Bharata` which is also correct in `Devanagri` as well as `Hindi` .

**Comment by bilashsaha** [comment]
@ronaldtse NVM. I had found a way for the above problem. Implementing that.

**Comment by ronaldtse** [comment]
> and the problem is how to determine that one word is a name/noun or a simple verb/adjective using regular expression? Or we shall always think that its a name

Very good point. We can't tell unless it is given to us as an input option (input = [string_to_transliterate, type_of_string]). In the future we want to use machine learning to identify the parts of speech and proper nouns, but now we don't have a way.

Did you find a way to do so?

**Comment by bilashsaha** [comment]
I found a way analyzing a good set of data so that actually this rule applies if any word ends with a consonant. The rule they specified tells us that the name word only will follow the rule but actually most of the words in Devanagari ends with a vowel but those who ends with a consonant, we can remove the implicit `a`  and that way the word is more appropriate in pronunciation. So I am applying it as a general rule for now. It would serve our purpose for this time.

But Yes to be perfect exactly with the rule we have to make a way to detect the proper nouns.

**Comment by ronaldtse** [comment]
@bilashsaha that's a great discovery! In this case, is it possible to add this "implementation note" to the systems (in the yaml) where this rule applies (and where named entities are transliterated differently)? Thanks.

**Comment by bilashsaha** [comment]
I will add proper notes and examples as well.

**Comment by ronaldtse** [comment]
Fixed.

<img width="279" alt="Screen Shot 2020-11-23 at 3 39 59 PM" src="https://user-images.githubusercontent.com/11865/99938135-26923500-2da2-11eb-90cd-2536914f15b4.png">
