### ISSUE TITLE
Ukrainian System `un-ukr-Cyrl-Latn-1998`

### ISSUE THREAD

**Issue by webdev778** [interscript/jsdemo.interscript.com#64]
The result:
![image](https://user-images.githubusercontent.com/28761746/101859980-1787f100-3bb0-11eb-95d7-6a476e5731a9.png)

The UN poster doc:
![image](https://user-images.githubusercontent.com/28761746/101860005-2a022a80-3bb0-11eb-8be6-9db1f80cdfe1.png)

the additional 'y' character there

_Originally posted by @webdev778 in https://github.com/interscript/jsdemo.interscript.com/issues/58#issuecomment-742951576_

**Comment by ronaldtse** [comment]
@CAMOBAP can you have look at this? I believe you wrote the original system.

**Comment by CAMOBAP** [comment]
I suppose the title is wrong because it pointed to `un-ukr-Cyrl-Latn-1998` while on the screenshots we see `ua-ukr-Cyrl-Latn-2007`, @ronaldtse @webdev778 correct me if I wrong.

If we talk about `un-ukr-Cyrl-Latn-1998`, I'm sure that it's implemented correctly `un-ukr-Cyrl-Latn-1998`, because there is a simple table of rules, there are no exception declared:

<img width="638" alt="Screen Shot 2021-01-26 at 8 33 50 AM" src="https://user-images.githubusercontent.com/2169738/105804817-c68e5980-5fb1-11eb-98f6-723f95de9836.png">

I will check `ua-ukr-Cyrl-Latn-2007`...

**Comment by ronaldtse** [comment]
I'm not sure whether the jsdemo site refers to the wrong system, or the system itself is wrong, or the text originally from the UN poster is wrong. I'll leave it to you to make the decision 😉 Thanks!

**Comment by CAMOBAP** [comment]
Well let me summarize my notes:
 - It's still not clear where the first screenshot comes from.
 - I have double-checked `un-ukr-Cyrl-Latn-1998` again and I'm not sure that it's implemented correctly at all because on the screenshot above we have 3 columns for GOST, BGN/PCGN, and French. Which once corresponds to `UN`? I have no idea, but at the time when I implemented it I selected BGN/PCGN
 - Per wiki https://en.wikipedia.org/wiki/Ukraine `Ukrayina` looks like correct romanization (looks like BGN/PCGN)
 - Also per another page https://en.wikipedia.org/wiki/Kyiv `Kyyiv` is correct BGN/PCGN romanization

All this research makes me feel that we must drop `un-ukr-Cyrl-Latn-1998` at all because it's just describe other schemes but doesn't introduce an own one.

@ronaldtse @webdev778 how do you think, should we remove `un-ukr-Cyrl-Latn-1998`?

**Comment by ronaldtse** [comment]
This image comes from the UN Poster. When the UN Poster was created, UN has adopted the Ukrainian national 2007 system. i.e. UN Ukranian system here == Ukraine national 2007 system (`ua-ukr-Cyrl-Latn-2007`).

> It's still not clear where the first screenshot comes from.

The screenshot comes from the "UN Poster": https://github.com/interscript/interscript/issues/438

This is supposed to reflect the "national 2007" system.

> I have double-checked un-ukr-Cyrl-Latn-1998 again and I'm not sure that it's implemented correctly at all because on the screenshot above we have 3 columns for GOST, BGN/PCGN, and French. Which once corresponds to UN? I have no idea, but at the time when I implemented it I selected BGN/PCGN

There is no UN here -- "national 2007" means the "national Romanization system of Ukraine in 2007", so it is supposed to be `ua-ukr-Cyrl-Latn-2007` not 1998 here. (Note it is "UA" code not "UN").

In addition, here the `un-ukr-Cyrl-Latn-1998` system here is supposed to follow GOST for Ukranian (the GOST column with "uk"): not BGN/PCGN.

> Per wiki https://en.wikipedia.org/wiki/Ukraine Ukrayina looks like correct romanization (looks like BGN/PCGN)

On Wikipedia there is not much understanding of correct assignment of transliteration systems.

> Also per another page https://en.wikipedia.org/wiki/Kyiv Kyyiv is correct BGN/PCGN romanization

Yes but here the system is "national 2007", not BGN/PCGN. BGN/PCGN 1965 (the one quoted in the original UN image) is a separate system: https://github.com/interscript/interscript/blob/master/maps/bgnpcgn-ukr-Cyrl-Latn-1965.yaml

**Comment by CAMOBAP** [comment]
@ronaldtse fixed https://github.com/interscript/interscript/pull/698

**Comment by CAMOBAP** [comment]
@ronaldtse just reviewed the comment history, to me it looks like we can close this one

**Comment by ronaldtse** [comment]
Thanks!
